// Define the specific status types used in the PO model
export type PoStatus = 'DRAFT' | 'SENT' | 'RECEIVED_PARTIAL' | 'RECEIVED_FULL' | 'CANCELLED';


/**
 * Interface for a single item within a Purchase Order.
 * Maps to the Django PurchaseOrderItem model.
 */
export interface PurchaseOrderItem {
    id?: number; // Optional if creating
    purchase_order?: number; // Foreign Key to parent PO
    product: number; // Foreign Key to the Product

    // Display fields fetched from Django serializer
    product_name?: string;

    quantity_ordered: number;
    unit_cost: number;
    line_total?: number; // Calculated field

    // Fields for tracking reception
    quantity_received_sum?: number; // Total received so far
    is_fully_received?: boolean;
}

/**
 * Interface for the main Purchase Order model.
 * Maps to the Django PurchaseOrder model.
 */
export interface PurchaseOrder {
    id?: number; // Optional if creating
    supplier: number; // Foreign Key to Supplier

    // Display fields fetched from Django serializer
    supplier_name?: string;
    po_number?: string;

    po_date?: string; // Date of creation (auto-generated by DRF)
    expected_delivery_date: string;

    order_total?: number; // Calculated field

    po_status: PoStatus;
    po_status_display?: string; // Human-readable status

    // The nested items array (PurchaseOrderItem)
    items: PurchaseOrderItem[];

    created_by?: number; // User ID
    created_by_username?: string;
}


// Optionally, define simple interfaces for lookup data for type safety
export interface Product {
    id: number;
    name: string;
}

export interface Supplier {
    id: number;
    name: string;
    email: string;
    phone: string;
    address: string;

}

export interface SupplierData {
    id: number;
    name: string;
    email: string;
    phone: string;
    address: string;
    created_at: string;

}

export interface ReceptionPayload {
  purchase_order_item: number;
  quantity_received: number;
  decayed_products: number;
}

// Full Reception Record (what the GET endpoint returns)
export interface ReceptionRecord extends ReceptionPayload {
  id: number;
  product_name: string; // Display field for the item
  received_by_name: string;
  reception_date: string;
}

export interface StockReception {
    id?: number;
    purchase_order_item: number;
    quantity_received: number;
    decayed_products: number;
    reception_date?: string;
    received_by?: number;
}

/**
 * @interface AvailableItemOption
 * Defines the simplified structure used for populating the Purchase Order Item dropdown
 * in the Stock Reception form. It maps a complex PO Item object to the essential
 * data needed for display and submission.
 */
export interface AvailableItemOption {
  /**
   * The unique ID of the Purchase Order Line Item.
   * This value is sent as 'purchase_order_item' in the API payload.
   */
  id: number;

  /**
   * The user-friendly string displayed in the dropdown selector.
   * (e.g., "PO #ORD-2025-0001 - LVDC (Qty Left: 13)")
   */
  display: string;

  /**
   * The Purchase Order's human-readable number (e.g., "#ORD-2025-0001").
   * Used for generating the display string.
   */
  po_number: string;
}


export interface OrderGroup {
    group: string; // e.g., "Current Month" or "September 2025"
    data: PurchaseOrder[];
}
