// Define the specific status types used in the PO model
export type PoStatus = 'DRAFT' | 'SENT' | 'RECEIVED_PARTIAL' | 'RECEIVED_FULL' | 'CANCELLED';

/**
 * Interface for a single item within a Purchase Order.
 * Maps to the Django PurchaseOrderItem model.
 */
export interface PurchaseOrderItem {
    id?: number; // Optional if creating
    purchase_order?: number; // Foreign Key to parent PO
    product: number; // Foreign Key to the Product

    // Display fields fetched from Django serializer
    product_name?: string;

    quantity_ordered: number;
    unit_cost: number;
    line_total?: number; // Calculated field

    // Fields for tracking reception
    quantity_received_sum?: number; // Total received so far
    is_fully_received?: boolean;
}

/**
 * Interface for the main Purchase Order model.
 * Maps to the Django PurchaseOrder model.
 */
export interface PurchaseOrder {
    id?: number; // Optional if creating
    supplier: number; // Foreign Key to Supplier

    // Display fields fetched from Django serializer
    supplier_name?: string;

    po_date?: string; // Date of creation (auto-generated by DRF)
    expected_delivery_date: string;

    order_total?: number; // Calculated field

    po_status: PoStatus;
    po_status_display?: string; // Human-readable status

    // The nested items array (PurchaseOrderItem)
    items: PurchaseOrderItem[];

    created_by?: number; // User ID
    created_by_username?: string;
}

/**
 * Interface for the Stock Reception model.
 * Maps to the Django StockReception model.
 * Used for the reception form.
 */
export interface StockReception {
    id?: number;

    // Foreign key to the specific line item being received
    purchase_order_item: number;

    quantity_received: number;
    decayed_products: number;

    // Auto-generated fields
    reception_date?: string;
    received_by?: number;
}

// Optionally, define simple interfaces for lookup data for type safety
export interface Product {
    id: number;
    name: string;
    // ...
}

export interface Supplier {
    id: number;
    name: string;
    // ...
}
